name = "diskflags"
description = "Manage small files to flag conditions"
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT"
website = ""
tags = ["flag", "disk", "file"]
